version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cits5206_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: cits5206_flask
    env_file: .env
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python dbTesting.py && flask run --host=0.0.0.0"
    volumes:
      - .:/app

volumes:
  pgdata:
